### ISSUE TITLE
Unknown input type github

### ISSUE THREAD

**Issue by hraban** [Mic92/flake-linter#1]
## Description

I get the error from the title when running this locally. Not sure how it's possible, given the source code has a clear "github" case right there...

## Reproduce

Example repo but this happens on all repos I've tried it with

```
mbp23:tmp user$ git clone https://github.com/Mic92/flake-linter
Cloning into 'flake-linter'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
Receiving objects: 100% (16/16), 6.00 KiB | 6.00 MiB/s, done.
Resolving deltas: 100% (1/1), done.
remote: Total 16 (delta 1), reused 12 (delta 1), pack-reused 0
mbp23:tmp user$ cd flake-linter/
mbp23:flake-linter user$ nix run github:Mic92/flake-linter
Unknown input type github
Unknown input type github
Unknown input type github
```

## Details

mac multi user, not sure what other details can be useful here. If you have a debug version I"m happy to try it.

**Comment by Mic92** [comment]
Stupid regression after refactoring the support...
